KA14/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('login_system.urls')),
    path('vendor/',include('vendor.urls')),
    path('',include('helloWorld.urls')),
    path('vendor_list/',include('vendor_list.urls'),name = "vendor_list"),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vendor_list/urls.py
from django.urls import path, include
from . import views

app_name = "vendor-list"

urlpatterns = [
        path("", views.vendor_list_page, name="vendor-list-page"),
        path("json/", views.vendor_list_json, name="vendor-list-json"),
]

vendor_list/models.py
from django.db import models

# Create your models here.

vendor_list/views.py
from django.shortcuts import render,redirect
from vendor.models import Vendor
from .form import Vendor_form
from django.http import JsonResponse
from django.http import HttpResponse
from django.core.serializers import serialize
from vendor.models import Vendor
# Create your views here.

# def vendor_list_page(request):
#     vendors = Vendor.objects.all()
#     return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, 'counter':range(3)})

def vendor_list_page(request):
    if request.method=="POST":
        form = Vendor_form(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect("/vendor_list/")
            # vendor = Vendor(
            #     name = form.cleaned_data['name'],
            #     info = form.cleaned_data['info'],
            #     price_level = form.cleaned_data['price_level'],
            #     food_type = form.cleaned_data['food_type'],
            #     website = form.cleaned_data['website'],
            #     email = form.cleaned_data['email'],
            #     phone = form.cleaned_data['phone'],
            #     vendor_picture = form.cleaned_data['vendor_picture'],
            # )
            # vendor.save()
        vendors = Vendor.objects.all()    
        return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, "forms":form}) 
    form = Vendor_form()
    vendors = Vendor.objects.all()    
    return render(request,"vendor_list/vendor_page.html", {'vendors':vendors, "forms":form})

def vendor_list_json(request):
    vendor = Vendor.objects.all()
    vendor_list = serialize('json',vendor)
    # return JsonResponse(vendor_list,safe=False)
    return HttpResponse(vendor_list,content_type="text/json-comment-filtered")

vendor_list/templates/vendor_list/vendor_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<script>
$(document).ready(function(){
    $(".col-card").hover(
        function(){
            $(this).toggleClass("hover-card");
        },
        function(){
            $(this).toggleClass("hover-card");
    });

    $(".col-card").mousedown(function(){
        $(this).toggleClass("hover-card");
    });

    $(".col-card").mouseup(function(){
        $(this).toggleClass("hover-card");
    });

    $.ajax({
        url:"{% url 'vendor-list:vendor-list-json' %}",
        datatype: "jsonp",
        success: function(data){
            console.log(data[0].fields.name);
            $(".theCount").empty()
            $(".theCount").append(
                data.length
            )
        }
    });
});
</script>

<div class="container" id="vendors-container">
    <div class="row" id="add-vendor" style="max-width: 100%"></div>
        {% if request.user.is_staff %}
            <button type="button" class="btn no-style ml-auto" data-toggle="modal" data-target="#exampleModalCenter">
                + Add Vendor
            </button>
        {% endif %}
    </div>
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalCenterTitle">Add Vendor</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
          </div>
            <form action="{% url 'vendor-list:vendor-list-page' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
              <div class="modal-body">
                    <div class="form-group">
                        {{ forms.name.errors }}
                        <label for="id_name">{{ forms.name.label }}</label>
                        {{ forms.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_star_ammount">{{ forms.info.label }}</label>
                        <div class="input-group">
                            {{ forms.info.errors }}
                            {{ forms.info }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.website.label }}</label>
                        <div class="input-group">
                            {{ forms.website.errors }}
                            {{ forms.website }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.email.label }}</label>
                        <div class="input-group">
                            {{ forms.email.errors }}
                            {{ forms.email }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.phone.label }}</label>
                        <div class="input-group">
                            {{ forms.phone.errors }}
                            {{ forms.phone }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.price_level.label }}</label>
                        <div class="input-group">
                            {{ forms.price_level.errors }}
                            {{ forms.price_level }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.food_type.label }}</label>
                        <div class="input-group">
                            {{ forms.foor_type.errors }}
                            {{ forms.food_type }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_comment">{{ forms.vendor_picture.label }}</label>
                        <div class="input-group">
                            {{ forms.vendor_picture.errors }}
                            {{ forms.vendor_picture }}
                        </div>
                    </div>
                </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn" style="background-color:pink">Add Vendor</button>
              </div>
            </form>
        </div>
      </div>
    </div>

    <div class="row justify-content-center mx-auto" id="vendors-lists">
    {% for vendor in vendors %}
        <div class="col-12 col-4 col-card">
            <div class="card">
                <img class="card-img-top" src="{{ vendor.vendor_picture.url }}" alt="Card image cap">
                <div class="card-body">
                    <a href="/vendor/{{ vendor.slug }}"><h1 class="card-name">{{ vendor.name }}</h1></a>
                    {{ vendor.get_star_ammount }} <img class="img-fluid card-star my-2" src="{% static 'vendor/Star_4.svg' %}" alt="stars">
                    <p class="card-dollar">{{ vendor.get_dollars }}</p>
                    <p class="card-text">{{ vendor.info }}</p>
                </div>
            </div>
        </div>   
    {% endfor %}
    </div>

    <div class="vendor-count">
        <h2>Our Vendors: </h2>
        <div id="count-box">
            <h1 class="theCount">0</h1>
        </div>
        <h2>and still increasing</h2>
    </div>

{% endblock %}